/*{
    "DESCRIPTION": "Sets the alpha channel to 0",
    "CREDIT": "Generated by Nuvotion",
    "ISFVSN": "2.0",
    "CATEGORIES": [
        "Basic"
    ],
    "INPUTS": []
}*/

void main() {
    gl_FragColor = vec4(0.0, 0.0, 0.0, 0.0);
}